DROP TABLE PEDIDOS_ITENS;
COMMIT;
DROP TABLE PEDIDOS;
COMMIT;
DROP TABLE PRODUTOS;
COMMIT;
DROP TABLE CLIENTES;
COMMIT;

----

CREATE TABLE CLIENTES (
    ID             INTEGER NOT NULL,
    NOME_FANTASIA  VARCHAR(150) NOT NULL,
    RAZAO_SOCIAL   VARCHAR(150) NOT NULL,
    CNPJ           VARCHAR(14) NOT NULL,
    ENDERECO       VARCHAR(300) NOT NULL,
    TELEFONE       VARCHAR(11) NOT NULL
);
ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (ID);

----

CREATE TABLE PRODUTOS (
    ID         INTEGER NOT NULL,
    DESCRICAO  VARCHAR(100) NOT NULL,
    MARCA      VARCHAR(30),
    PRECO      DECIMAL(15,2) NOT NULL
);
ALTER TABLE PRODUTOS ADD CONSTRAINT PK_PRODUTOS PRIMARY KEY (ID);

----

CREATE TABLE PEDIDOS (
    ID           INTEGER NOT NULL,
    ID_CLIENTE   INTEGER NOT NULL,
    VALOR_TOTAL  DECIMAL(15,2) NOT NULL,
    DATA_HORA    TIMESTAMP NOT NULL
);
ALTER TABLE PEDIDOS ADD CONSTRAINT PK_PEDIDOS PRIMARY KEY (ID);
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID);

----

CREATE TABLE PEDIDOS_ITENS (
    ID          INTEGER NOT NULL,
    ID_PEDIDO   INTEGER NOT NULL,
    ID_PRODUTO  INTEGER NOT NULL,
    QUANTIDADE  INTEGER NOT NULL,
    PRECO       DECIMAL(15,2) NOT NULL
);
ALTER TABLE PEDIDOS_ITENS ADD CONSTRAINT PK_PEDIDOS_ITENS PRIMARY KEY (ID);
ALTER TABLE PEDIDOS_ITENS ADD CONSTRAINT FK_PEDIDOS_ITENS_ID_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS (ID);
ALTER TABLE PEDIDOS_ITENS ADD CONSTRAINT FK_PEDIDOS_ITENS_ID_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS (ID);
